const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const B = (en, pa) => `<span class="en">${en}</span><span class="pa" lang="pa">${pa}</span>`;
const arrow = '<span aria-hidden="true">↗</span>';
const definitions = [
 ['cardiology','Cardiology','ਦਿਲ ਦੀ ਦੇਖਭਾਲ','Your heart.','In expert hands.','ਦਿਲ ਦੀ ਬਿਹਤਰ ਦੇਖਭਾਲ।','ਸਹੀ ਫ਼ੈਸਲੇ ਵੱਲ ਪਹਿਲਾ ਕਦਮ।','Understand your heart health with a specialist who helps you make sense of your symptoms, reports and treatment options.','ਆਪਣੇ ਲੱਛਣਾਂ, ਰਿਪੋਰਟਾਂ ਅਤੇ ਇਲਾਜ ਦੇ ਵਿਕਲਪਾਂ ਬਾਰੇ ਦਿਲ ਦੇ ਮਾਹਿਰ ਨਾਲ ਗੱਲ ਕਰੋ।','dr-sahil.jpeg','Heart evaluation · Interventional care · Second opinions'],
 ['orthopaedics','Orthopaedics','ਹੱਡੀਆਂ ਅਤੇ ਜੋੜ','More movement.','More life.','ਬਿਹਤਰ ਚੱਲਣ ਵੱਲ ਕਦਮ।','ਜੀਵਨ ਵਿੱਚ ਵੱਧ ਆਜ਼ਾਦੀ।','From persistent joint pain to a sports injury, get a specialist assessment and a treatment plan built around your mobility goals.','ਜੋੜਾਂ ਦੇ ਦਰਦ ਜਾਂ ਖੇਡ ਦੀ ਸੱਟ ਲਈ ਮਾਹਿਰ ਦੀ ਸਲਾਹ ਅਤੇ ਆਪਣੀ ਲੋੜ ਮੁਤਾਬਕ ਇਲਾਜ ਯੋਜਨਾ ਲਵੋ।','dr-shubhang.jpg','Joint care · Robotic surgery · Sports injuries'],
 ['urology','Urology','ਯੂਰੋਲੋਜੀ','Personal concerns.','Expert care.','ਮਾਹਿਰ ਦੀ ਦੇਖਭਾਲ।','ਆਪਣੀ ਸਿਹਤ ਨੂੰ ਤਰਜੀਹ ਦਿਓ।','Get clear answers about kidney stones, prostate problems and urinary concerns, with personalised guidance from a urology specialist.','ਪੱਥਰੀ, ਪ੍ਰੋਸਟੇਟ ਅਤੇ ਪਿਸ਼ਾਬ ਦੀਆਂ ਸਮੱਸਿਆਵਾਂ ਲਈ ਯੂਰੋਲੋਜੀ ਦੇ ਮਾਹਿਰ ਤੋਂ ਸਲਾਹ ਲਵੋ।','dr-satinder.jpeg','Kidney stones · Prostate care · Urological surgery'],
 ['nephrology','Nephrology','ਗੁਰਦਿਆਂ ਦੀ ਦੇਖਭਾਲ','Your kidney health.','Our complete focus.','ਤੁਹਾਡੇ ਗੁਰਦਿਆਂ ਦੀ ਸਿਹਤ।','ਸਾਡੀ ਖ਼ਾਸ ਦੇਖਭਾਲ।','An abnormal report can leave you with questions. Speak to a kidney specialist about evaluation, ongoing care and dialysis planning.','ਗੁਰਦਿਆਂ ਦੀ ਜਾਂਚ, ਲਗਾਤਾਰ ਦੇਖਭਾਲ ਅਤੇ ਡਾਇਲਸਿਸ ਦੀ ਯੋਜਨਾ ਲਈ ਮਾਹਿਰ ਨਾਲ ਗੱਲ ਕਰੋ।','dr-sanjay.jpeg','Kidney evaluation · Dialysis · Ongoing support'],
 ['gastroenterology','Gastroenterology','ਪੇਟ ਅਤੇ ਜਿਗਰ','Feel understood.','Find your next step.','ਪੇਟ ਅਤੇ ਜਿਗਰ ਦੀ ਸਿਹਤ।','ਸਹੀ ਸਮਝ ਨਾਲ ਸ਼ੁਰੂਆਤ।','Make sense of digestive discomfort, liver reports or an advised procedure with specialist evaluation and a clear next step.','ਪੇਟ ਦੀ ਤਕਲੀਫ਼, ਜਿਗਰ ਦੀਆਂ ਰਿਪੋਰਟਾਂ ਜਾਂ ਸਲਾਹ ਦਿੱਤੀ ਜਾਂਚ ਬਾਰੇ ਮਾਹਿਰ ਤੋਂ ਸਮਝੋ।','dr-anuj.jpeg','Digestive care · Liver health · Endoscopy']
];
const contentPath = path.join(root, 'landing-content.json');
const content = JSON.parse(fs.readFileSync(contentPath,'utf8'));
const departments = (prefix, className='') => definitions.map((d,i)=>`<a class="${className}" href="${prefix}${d[0]}-treatment/"><span class="service-number">0${i+1}</span><div><h3>${B(d[1],d[2])}</h3><p>${d[10]}</p></div>${arrow}</a>`).join('') + `<a class="service-card service-consult" href="#book"><span class="service-number">✧</span><div><h3>${B('Let’s find your next step.','ਅਗਲਾ ਕਦਮ ਚੁਣੀਏ।')}</h3><p>${B('Not sure which specialist to see? Tell our care team what’s troubling you. We’ll help you get started.','ਸਹੀ ਮਾਹਿਰ ਚੁਣਨ ਲਈ ਆਪਣੀ ਤਕਲੀਫ਼ ਸਾਡੀ ਟੀਮ ਨੂੰ ਦੱਸੋ।')}</p><span class="text-link">${B('Speak to our team','ਸਾਡੀ ਟੀਮ ਨਾਲ ਗੱਲ ਕਰੋ')} ${arrow}</span></div></a>`;
function page(c, d, home=false) {
 const prefix=home?'./':'../';
 const name=home?B('NHS Hospital','NHS ਹਸਪਤਾਲ'):c.name;
 const title=home?'Specialist care.':'Specialist '+d[1].toLowerCase()+' care.';
 const headline=home?B('Expertise you need.','ਤੁਹਾਡੀ ਸਿਹਤ ਲਈ')+'<br><em>'+B('Care you deserve.','ਖ਼ਾਸ ਦੇਖਭਾਲ।')+'</em>':B(d[3],d[5])+'<br><em>'+B(d[4],d[6])+'</em>';
 const description=home?B('The right specialist. A clear plan. Care that stays with you. Find your next step at NHS Hospital, Jalandhar.','ਸਹੀ ਮਾਹਿਰ, ਸਪੱਸ਼ਟ ਯੋਜਨਾ ਅਤੇ ਤੁਹਾਡੇ ਲਈ ਦੇਖਭਾਲ। NHS ਹਸਪਤਾਲ, ਜਲੰਧਰ ਵਿੱਚ ਸਲਾਹ ਲਵੋ।'):B(d[7],d[8]);
 const photo=home?'nhs-hospital-building.jpg':d[9];
 const department=home?'General enquiry':d[1];
 const options=home?definitions.map(d=>`<option value="${d[1]}">${d[1]} / ${d[2]}</option>`).join(''):c.options.map(o=>`<option>${o}</option>`).join('');
 const heroForm=`<form class="hero-form" id="hero-form" action="https://app.formester.com/forms/xh1pxuMQJ/submissions" method="POST"><input type="hidden" name="_redirect" value="https://enquire.nhshospital.in/thank-you"><input type="hidden" name="department" value="${department}"><div class="hero-form-heading"><div><span class="form-kicker">${B('START WITH A CONVERSATION','ਗੱਲਬਾਤ ਨਾਲ ਸ਼ੁਰੂਆਤ ਕਰੋ')}</span><h2>${B('Request a callback','ਕਾਲ ਲਈ ਬਿਨਤੀ ਕਰੋ')}</h2></div><p>${B('Our team will call you during OPD hours.','ਸਾਡੀ ਟੀਮ OPD ਸਮੇਂ ਤੁਹਾਨੂੰ ਫ਼ੋਨ ਕਰੇਗੀ।')}</p></div><div class="hero-form-fields"><label class="hero-field" for="hero-name"><span>${B('Full name','ਪੂਰਾ ਨਾਂ')}</span><input id="hero-name" name="patient_name" autocomplete="name" placeholder="Your full name" data-placeholder-en="Your full name" data-placeholder-pa="ਤੁਹਾਡਾ ਪੂਰਾ ਨਾਂ" required maxlength="100"></label><label class="hero-field" for="hero-mobile"><span>${B('Mobile number','ਮੋਬਾਈਲ ਨੰਬਰ')}</span><span class="hero-phone-input"><span aria-hidden="true">+91</span><input id="hero-mobile" name="mobile" type="tel" inputmode="numeric" autocomplete="tel-national" placeholder="10-digit number" data-placeholder-en="10-digit number" data-placeholder-pa="10 ਅੰਕਾਂ ਦਾ ਨੰਬਰ" pattern="[6-9][0-9]{9}" maxlength="10" title="Enter a valid 10-digit Indian mobile number" required></span></label><label class="hero-field" for="hero-problem"><span>${B(home?'Specialty':'Your concern',home?'ਵਿਭਾਗ':'ਤੁਹਾਡੀ ਸਮੱਸਿਆ')}</span><select id="hero-problem" name="problem" required><option value="">${home?'Choose a specialty / ਵਿਭਾਗ ਚੁਣੋ':'Choose your concern / ਸਮੱਸਿਆ ਚੁਣੋ'}</option>${options}<option value="Help me choose">Not sure — help me choose / ਚੁਣਨ ਵਿੱਚ ਮਦਦ ਕਰੋ</option></select></label><button class="button primary" type="submit">${B('Request callback','ਕਾਲ ਲਈ ਬਿਨਤੀ')} ${arrow}</button></div><label class="hero-consent"><input type="checkbox" name="consent" value="yes" required><span>${B('I agree to be contacted about this enquiry and have read the','ਮੈਂ ਇਸ ਬਿਨਤੀ ਬਾਰੇ ਸੰਪਰਕ ਲਈ ਸਹਿਮਤ ਹਾਂ ਅਤੇ ਪੜ੍ਹੀ ਹੈ')} <a href="${prefix}privacy.html#privacy">${B('privacy policy','ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ')}</a>.</span></label></form>`;
 const specialist=home?`<section class="section shell" id="doctor"><div class="section-heading"><div><span class="eyebrow">${B('People behind your care','ਤੁਹਾਡੀ ਦੇਖਭਾਲ ਦੇ ਮਾਹਿਰ')}</span><h2>${B('Meet your specialists.','ਆਪਣੇ ਮਾਹਿਰਾਂ ਨੂੰ ਮਿਲੋ।')}</h2></div><p>${B('Find the right expertise for your concern. Explore a service to learn more about your consultant.','ਆਪਣੀ ਸਮੱਸਿਆ ਲਈ ਸਹੀ ਮਾਹਿਰ ਚੁਣੋ।')}</p></div><div class="doctors">${content.map((c,i)=>`<a class="doctor-card" href="${prefix}${c.key}-treatment/"><div class="doctor-photo"><img src="${prefix}assets/${definitions[i][9]}" alt="${c.name.replace(/<span class="pa">[\s\S]*?<\/span>/,'').replace(/<[^>]+>/g,'')}" loading="lazy"></div><div><small>${B(definitions[i][1],definitions[i][2])}</small><h3>${c.name}</h3><span class="text-link">${B('Meet your doctor','ਡਾਕਟਰ ਬਾਰੇ ਜਾਣੋ')} ${arrow}</span></div></a>`).join('')}</div></section>`:
 `<section class="section doctor-section" id="doctor"><div class="shell doctor-layout"><div class="portrait"><img src="${prefix}assets/${photo}" alt="${c.name.replace(/<span class="pa"[^>]*>[\s\S]*?<\/span>/,'').replace(/<[^>]+>/g,'')}" loading="lazy"><span class="portrait-label">NHS Hospital · Jalandhar</span></div><div><span class="eyebrow">${B('Meet your specialist','ਆਪਣੇ ਮਾਹਿਰ ਨੂੰ ਮਿਲੋ')}</span><h2>${name}</h2>${c.paragraphs.map((p,i)=>`<p class="${i===0?'doctor-role':'doctor-bio'}">${p}</p>`).join('')}<a class="button primary" href="#book">${B('Request an appointment','ਮੁਲਾਕਾਤ ਲਈ ਬਿਨਤੀ ਕਰੋ')} ${arrow}</a></div></div></section>`;
 const treatments=home?departments(prefix,'service-card'):c.treatments.map((t,i)=>`<article class="service-card"><span class="service-number">0${i+1}</span><div><h3>${t.title}</h3><p>${t.description}</p><a class="text-link" href="#book">${B('Discuss with our team','ਸਾਡੀ ਟੀਮ ਨਾਲ ਗੱਲ ਕਰੋ')} ${arrow}</a></div></article>`).join('');
 return `<!doctype html>
<html lang="en" data-lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${home?'NHS Hospital | Specialist Care in Jalandhar':d[1]+' in Jalandhar | NHS Hospital'}</title><meta name="description" content="${home?'Explore specialist care at NHS Hospital, Jalandhar. Request a consultation with our cardiology, orthopaedics, urology, kidney and digestive health teams.':d[7]}"><meta name="theme-color" content="#173b32"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&family=Instrument+Serif:ital@0;1&family=Noto+Sans+Gurmukhi:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${prefix}assets/landing.css"><script src="${prefix}assets/landing.js" defer></script></head>
<body class="${home?'home-page':c.key+'-page'}"><a class="skip-link" href="#main">Skip to content</a>
<div class="utility"><div class="shell"><span>${B('Nasa &amp; Hub Superspeciality Hospital · Jalandhar','ਨਾਸਾ ਅਤੇ ਹੱਬ ਸੁਪਰਸਪੈਸ਼ਲਿਟੀ ਹਸਪਤਾਲ · ਜਲੰਧਰ')}</span><a href="tel:+911814707700"><span class="live-dot"></span>${B('24/7 emergency','24 ਘੰਟੇ ਐਮਰਜੈਂਸੀ')} <strong>0181-4707700</strong></a></div></div>
<header><div class="shell navigation"><a class="brand" href="${prefix}" aria-label="NHS Hospital home"><img src="${prefix}assets/logo.png" alt="NHS Hospital"></a><nav aria-label="Main navigation"><a href="#treatments">${B(home?'Specialties':'Treatments',home?'ਵਿਭਾਗ':'ਇਲਾਜ')}</a><a href="#doctor">${B(home?'Our doctors':'Your specialist',home?'ਸਾਡੇ ਡਾਕਟਰ':'ਤੁਹਾਡਾ ਮਾਹਿਰ')}</a><a href="#hospital">${B('Our hospital','ਸਾਡਾ ਹਸਪਤਾਲ')}</a></nav><div class="nav-actions"><div class="language" aria-label="Choose language"><button type="button" data-language="en" aria-pressed="true">EN</button><button type="button" data-language="pa" aria-pressed="false">ਪੰ</button></div><a class="button small primary" href="#hero-form">${B('Book a visit','ਮੁਲਾਕਾਤ')} ${arrow}</a></div></div></header>
<main id="main">
<section class="hero"><div class="shell hero-grid"><div class="hero-copy"><span class="eyebrow"><span class="live-dot"></span>${B(home?'NHS HOSPITAL · JALANDHAR':d[1]+' · NHS HOSPITAL',home?'NHS ਹਸਪਤਾਲ · ਜਲੰਧਰ':d[2]+' · NHS ਹਸਪਤਾਲ')}</span><h1>${headline}</h1><p class="hero-description">${description}</p><div class="hero-actions"><a class="button primary" href="#hero-form">${B('Book a consultation','ਸਲਾਹ ਲਈ ਬਿਨਤੀ ਕਰੋ')} ${arrow}</a><a class="hero-phone" href="tel:+911814633333"><small>${B('Speak to our care team','ਸਾਡੀ ਟੀਮ ਨਾਲ ਗੱਲ ਕਰੋ')}</small><strong>0181-4633333</strong></a></div><div class="hero-bottom"><span class="hero-line"></span><p>${B('Specialist expertise. Personal attention.','ਮਾਹਿਰ ਦੀ ਸਲਾਹ। ਤੁਹਾਡੇ ਲਈ ਖ਼ਾਸ ਧਿਆਨ।')}<br><span>${B('Every step of the way.','ਹਰ ਕਦਮ ਉੱਤੇ।')}</span></p></div></div>
<div class="hero-visual"><div class="image-frame"><img class="hero-photo" src="${prefix}assets/${home?'nhs-hospital-building.jpg':c.key==='orthopaedics'?'hospital-1.jpg':'nhs-doctor-consultation.jpg'}" alt="${home?'NHS Hospital, Jalandhar':c.key==='orthopaedics'?'Robotic joint surgery equipment and surgeon at NHS Hospital':'A patient consultation at NHS Hospital'}" fetchpriority="high"><div class="image-shade"></div><span class="image-caption">${B(home?'YOUR CARE. OUR COMMITMENT.':'REAL PEOPLE. PERSONALISED CARE.',home?'ਤੁਹਾਡੀ ਸਿਹਤ। ਸਾਡੀ ਜ਼ਿੰਮੇਵਾਰੀ।':'ਤੁਹਾਡੇ ਲਈ ਖ਼ਾਸ ਦੇਖਭਾਲ।')}</span></div><div class="visual-seal"><span aria-hidden="true">✧</span><small>${B('CARE BEYOND','ਸਿਹਤ ਲਈ')}</small><strong>${B('the ordinary','ਖ਼ਾਸ ਦੇਖਭਾਲ')}</strong></div><a class="expert-card" href="#doctor"><img class="expert-avatar" src="${prefix}assets/${photo}" alt="" width="72" height="72"><div><small>${B(home?'MEET YOUR CARE TEAM':'YOUR SPECIALIST',home?'ਆਪਣੀ ਟੀਮ ਨੂੰ ਮਿਲੋ':'ਤੁਹਾਡੇ ਮਾਹਿਰ')}</small><strong>${name}</strong><span>${home?B('Five specialties. One commitment to you.','ਪੰਜ ਵਿਭਾਗ। ਤੁਹਾਡੀ ਦੇਖਭਾਲ।'):B(d[1]+' · Jalandhar',d[2]+' · ਜਲੰਧਰ')}</span></div><span class="circle-arrow" aria-hidden="true">↗</span></a></div>${heroForm}</div></section>
<div class="care-strip"><div class="shell"><div><span class="strip-icon" aria-hidden="true">01</span><span><strong>${B('Specialist-led care','ਮਾਹਿਰਾਂ ਦੀ ਦੇਖਭਾਲ')}</strong><small>${B('Expertise for your individual needs','ਤੁਹਾਡੀ ਲੋੜ ਮੁਤਾਬਕ ਸਲਾਹ')}</small></span></div><div><span class="strip-icon" aria-hidden="true">02</span><span><strong>${B('Everything, in one place','ਇੱਕੋ ਥਾਂ ਦੇਖਭਾਲ')}</strong><small>${B('Consultation, diagnosis &amp; treatment','ਸਲਾਹ, ਜਾਂਚ ਅਤੇ ਇਲਾਜ')}</small></span></div><div><span class="strip-icon" aria-hidden="true">03</span><span><strong>${B('Here, around the clock','24 ਘੰਟੇ ਤੁਹਾਡੇ ਨਾਲ')}</strong><small>${B('24/7 emergency support','24 ਘੰਟੇ ਐਮਰਜੈਂਸੀ')}</small></span></div></div></div>
<section class="section shell" id="treatments"><div class="section-heading"><div><span class="eyebrow">${B(home?'Find your care':'Care built around you',home?'ਆਪਣੀ ਦੇਖਭਾਲ ਚੁਣੋ':'ਤੁਹਾਡੇ ਲਈ ਦੇਖਭਾਲ')}</span><h2>${B(home?'One hospital.\nA world of expertise.':'Specialist care.\nCentred on you.',home?'ਤੁਹਾਡੀ ਲੋੜ ਲਈ ਸਹੀ ਮਾਹਿਰ।':'ਤੁਹਾਡੀ ਸਮੱਸਿਆ ਲਈ ਸਲਾਹ ਅਤੇ ਇਲਾਜ।')}</h2></div><p>${B(home?'Start with what’s troubling you. Our specialist teams can help you understand your options.':'Explore the concerns our team evaluates. Your specialist will recommend the care appropriate for you.',home?'ਆਪਣੀ ਤਕਲੀਫ਼ ਬਾਰੇ ਸਾਡੀ ਮਾਹਿਰਾਂ ਦੀ ਟੀਮ ਨਾਲ ਗੱਲ ਕਰੋ।':'ਸਾਡੀ ਟੀਮ ਨਾਲ ਆਪਣੀ ਸਮੱਸਿਆ ਬਾਰੇ ਗੱਲ ਕਰੋ। ਇਲਾਜ ਦੀ ਸਲਾਹ ਜਾਂਚ ਤੋਂ ਬਾਅਦ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ।')}</p></div><div class="services">${treatments}</div><div class="help-line">${B('Not sure where to start? We’ll help you find the right department.','ਸਹੀ ਵਿਭਾਗ ਚੁਣਨ ਲਈ ਸਾਡੇ ਨਾਲ ਗੱਲ ਕਰੋ।')} <a href="tel:+911814633333">${B('Call our care team','ਸਾਡੀ ਟੀਮ ਨੂੰ ਫ਼ੋਨ ਕਰੋ')} ${arrow}</a></div></section>
${specialist}
<section class="section shell hospital-section" id="hospital"><div class="section-heading"><div><span class="eyebrow">${B('The place behind the care','ਦੇਖਭਾਲ ਦੀ ਥਾਂ')}</span><h2>${B('Thoughtfully equipped.\nPersonally delivered.','ਤੁਹਾਡੀ ਦੇਖਭਾਲ ਲਈ ਸਾਡਾ ਹਸਪਤਾਲ।')}</h2></div><p>${B('From your first consultation to specialist treatment, get to know the spaces and people behind your care.','ਜਲੰਧਰ ਵਿੱਚ ਸਾਡੇ ਹਸਪਤਾਲ ਦੀਆਂ ਅਸਲ ਤਸਵੀਰਾਂ ਵੇਖੋ।')}</p></div><div class="hospital-gallery"><figure class="gallery-main"><img src="${prefix}assets/nhs-doctor-consultation.jpg" alt="Doctor consultation at NHS Hospital" loading="lazy"><figcaption>${B('Time to listen. Space to understand.','ਤੁਹਾਡੀ ਗੱਲ ਸੁਣਨ ਅਤੇ ਸਮਝਣ ਲਈ।')}</figcaption></figure><figure><img src="${prefix}assets/nhs-modular-ot.jpg" alt="Modular operation theatre at NHS Hospital" loading="lazy"><figcaption>${B('Modular operation theatres','ਮਾਡਿਊਲਰ ਆਪਰੇਸ਼ਨ ਥੀਏਟਰ')}</figcaption></figure><figure><img src="${prefix}assets/nhs-opd-waiting-hall.jpg" alt="Outpatient waiting hall at NHS Hospital" loading="lazy"><figcaption>${B('Outpatient department','ਬਾਹਰੀ ਮਰੀਜ਼ ਵਿਭਾਗ')}</figcaption></figure></div></section>
<section class="section journey-section" id="how"><div class="shell"><div class="section-heading"><div><span class="eyebrow">${B('A simpler path to care','ਦੇਖਭਾਲ ਵੱਲ ਆਸਾਨ ਕਦਮ')}</span><h2>${B('Good care begins\nwith a conversation.','ਅਗਲਾ ਕਦਮ ਇਕੱਠੇ ਚੁੱਕੀਏ।')}</h2></div><p>${B('From your first enquiry to a conversation with your specialist, here’s how to get started.','ਬਿਨਤੀ ਤੋਂ ਮਾਹਿਰ ਦੀ ਸਲਾਹ ਤੱਕ, ਸ਼ੁਰੂਆਤ ਇਸ ਤਰ੍ਹਾਂ ਕਰੋ।')}</p></div><div class="steps">${[
 [B('Tell us what you need','ਆਪਣੀ ਸਮੱਸਿਆ ਦੱਸੋ'),B('Request a callback or call our appointment desk. Share the concern you’d like help with.','ਕਾਲ ਲਈ ਬਿਨਤੀ ਕਰੋ ਜਾਂ ਮੁਲਾਕਾਤ ਕਾਊਂਟਰ ਨੂੰ ਫ਼ੋਨ ਕਰੋ।')],
 [B('Meet your specialist','ਆਪਣੇ ਮਾਹਿਰ ਨੂੰ ਮਿਲੋ'),B('Bring your reports and current prescriptions. Discuss your symptoms and ask your questions.','ਰਿਪੋਰਟਾਂ ਅਤੇ ਦਵਾਈਆਂ ਦੀ ਸੂਚੀ ਲਿਆਓ। ਆਪਣੇ ਸਵਾਲ ਮਾਹਿਰ ਨੂੰ ਪੁੱਛੋ।')],
 [B('Understand your next step','ਅਗਲਾ ਕਦਮ ਸਮਝੋ'),B('Your doctor explains any recommended tests and treatment options for your individual needs.','ਡਾਕਟਰ ਤੁਹਾਡੀ ਲੋੜ ਮੁਤਾਬਕ ਜਾਂਚ ਅਤੇ ਇਲਾਜ ਦੇ ਵਿਕਲਪ ਸਮਝਾਉਣਗੇ।')]
 ].map((s,i)=>`<article><span class="step-number">0${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}</div></div></section>
<section class="section shell appointment-section" id="book"><div class="appointment-copy"><span class="eyebrow">${B('Your next step starts here','ਅਗਲਾ ਕਦਮ ਇੱਥੋਂ ਸ਼ੁਰੂ ਕਰੋ')}</span><h2>${B('Let’s talk about','ਆਪਣੇ ਸਵਾਲ ਲਿਆਓ।')}<br><em>${B('your health.','ਅਸੀਂ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਾਂਗੇ।')}</em></h2><p>${B('Leave your details and our appointment team will call you during OPD hours to help arrange your visit.','ਆਪਣੇ ਵੇਰਵੇ ਭੇਜੋ। ਸਾਡੀ ਟੀਮ OPD ਦੇ ਸਮੇਂ ਫ਼ੋਨ ਕਰਕੇ ਮੁਲਾਕਾਤ ਵਿੱਚ ਮਦਦ ਕਰੇਗੀ।')}</p><a class="appointment-phone" href="tel:+911814633333"><small>${B('Prefer to call?','ਫ਼ੋਨ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?')}</small><strong>0181-4633333 ${arrow}</strong></a><div class="visit-note"><span aria-hidden="true">⌖</span><p>${B('Near Sports College, 300 m from Kapurthala Chowk, Jalandhar, Punjab 144001','ਸਪੋਰਟਸ ਕਾਲਜ ਦੇ ਨੇੜੇ, ਕਪੂਰਥਲਾ ਚੌਕ ਤੋਂ 300 ਮੀਟਰ, ਜਲੰਧਰ, ਪੰਜਾਬ 144001')}</p></div><a class="text-link" href="https://wa.me/911814633333?text=${encodeURIComponent('Hello NHS Hospital, I would like to enquire about '+department+' consultation.')}" target="_blank" rel="noopener">${B('Enquire on WhatsApp','WhatsApp ਉੱਤੇ ਪੁੱਛੋ')} ${arrow}</a></div>
<form class="appointment-form" action="https://app.formester.com/forms/xh1pxuMQJ/submissions" method="POST"><span class="form-kicker">${B('LET’S PLAN YOUR VISIT','ਆਪਣੀ ਮੁਲਾਕਾਤ ਦੀ ਯੋਜਨਾ ਬਣਾਓ')}</span><h3>${B('Request a callback','ਕਾਲ ਲਈ ਬਿਨਤੀ ਕਰੋ')}</h3><p>${B('A little information. A helpful conversation.','ਆਪਣੇ ਵੇਰਵੇ ਦਿਓ ਅਤੇ ਸਾਡੇ ਨਾਲ ਗੱਲ ਕਰੋ।')}</p><input type="hidden" name="_redirect" value="https://enquire.nhshospital.in/thank-you"><input type="hidden" name="department" value="${department}"><label for="patient-name">${B('Full name','ਪੂਰਾ ਨਾਂ')}</label><input id="patient-name" name="patient_name" autocomplete="name" placeholder="Your full name" data-placeholder-en="Your full name" data-placeholder-pa="ਤੁਹਾਡਾ ਪੂਰਾ ਨਾਂ" required maxlength="100"><label for="mobile">${B('Mobile number','ਮੋਬਾਈਲ ਨੰਬਰ')}</label><div class="phone-input"><span>+91</span><input id="mobile" name="mobile" type="tel" inputmode="numeric" autocomplete="tel-national" placeholder="10-digit mobile number" data-placeholder-en="10-digit mobile number" data-placeholder-pa="10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ" pattern="[6-9][0-9]{9}" maxlength="10" title="Enter a valid 10-digit Indian mobile number" required></div><label for="problem">${B('How can we help?','ਅਸੀਂ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ?')}</label><select id="problem" name="problem" required><option value="">${home?'Choose a specialty / ਵਿਭਾਗ ਚੁਣੋ':'Choose your concern / ਆਪਣੀ ਸਮੱਸਿਆ ਚੁਣੋ'}</option>${options}<option value="Help me choose">Not sure — help me choose / ਚੁਣਨ ਵਿੱਚ ਮਦਦ ਕਰੋ</option></select><label class="consent"><input type="checkbox" name="consent" value="yes" required><span>${B('I agree to be contacted about this enquiry and have read the','ਮੈਂ ਇਸ ਬਿਨਤੀ ਬਾਰੇ ਸੰਪਰਕ ਲਈ ਸਹਿਮਤ ਹਾਂ ਅਤੇ ਪੜ੍ਹੀ ਹੈ')} <a href="${prefix}privacy.html#privacy">${B('privacy policy','ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ')}</a>.</span></label><button class="button primary" type="submit">${B('Request my callback','ਕਾਲ ਲਈ ਬਿਨਤੀ ਭੇਜੋ')} ${arrow}</button><small class="form-note">${B('Our team will confirm availability. This is an appointment enquiry.','ਸਾਡੀ ਟੀਮ ਮੁਲਾਕਾਤ ਦੀ ਉਪਲਬਧਤਾ ਦੀ ਪੁਸ਼ਟੀ ਕਰੇਗੀ।')}</small></form></section>
<section class="section shell faq-section" id="faq"><div><span class="eyebrow">${B('Before your visit','ਆਉਣ ਤੋਂ ਪਹਿਲਾਂ')}</span><h2>${B('A few helpful answers.','ਕੁਝ ਮਦਦਗਾਰ ਜਵਾਬ।')}</h2></div><div class="faqs">${[
 [B('What happens after I request a callback?','ਬਿਨਤੀ ਭੇਜਣ ਤੋਂ ਬਾਅਦ ਕੀ ਹੁੰਦਾ ਹੈ?'),B('Our appointment team will contact you during OPD hours to discuss your concern and available appointments. Your visit is confirmed by the team.','ਸਾਡੀ ਟੀਮ OPD ਸਮੇਂ ਸੰਪਰਕ ਕਰੇਗੀ ਅਤੇ ਮੁਲਾਕਾਤ ਦੀ ਪੁਸ਼ਟੀ ਕਰੇਗੀ।')],
 [B('Can I bring my reports for a second opinion?','ਕੀ ਮੈਂ ਦੂਜੀ ਰਾਏ ਲਈ ਰਿਪੋਰਟਾਂ ਲਿਆ ਸਕਦਾ ਹਾਂ?'),B('Yes. Bring your previous reports, scans and current prescriptions so your specialist can review your history.','ਹਾਂ। ਆਪਣੀਆਂ ਪੁਰਾਣੀਆਂ ਰਿਪੋਰਟਾਂ, ਸਕੈਨ ਅਤੇ ਦਵਾਈਆਂ ਦੀ ਸੂਚੀ ਨਾਲ ਲਿਆਓ।')],
 [B('How do I check insurance or cashless eligibility?','ਬੀਮੇ ਜਾਂ ਕੈਸ਼ਲੈਸ ਬਾਰੇ ਕਿਵੇਂ ਪੁੱਛਾਂ?'),B('Call our desk before your visit. The team can help you check your insurer or scheme and the documents needed. Coverage is subject to approval.','ਮੁਲਾਕਾਤ ਤੋਂ ਪਹਿਲਾਂ ਸਾਡੇ ਕਾਊਂਟਰ ਨੂੰ ਫ਼ੋਨ ਕਰੋ। ਬੀਮੇ ਦੀ ਮਨਜ਼ੂਰੀ ਅਤੇ ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼ਾਂ ਬਾਰੇ ਪੁੱਛੋ।')],
 [B('What if I need urgent medical attention?','ਜੇ ਮੈਨੂੰ ਤੁਰੰਤ ਡਾਕਟਰੀ ਮਦਦ ਦੀ ਲੋੜ ਹੈ?'),B('Call <a href="tel:+911814707700">0181-4707700</a> or go to your nearest emergency department. Please do not wait for a callback for an emergency.','0181-4707700 ਉੱਤੇ ਫ਼ੋਨ ਕਰੋ ਜਾਂ ਨੇੜੇ ਦੇ ਐਮਰਜੈਂਸੀ ਵਿਭਾਗ ਜਾਓ। ਕਾਲ ਦੀ ਉਡੀਕ ਨਾ ਕਰੋ।')]
 ].map(q=>`<details><summary>${q[0]}<span aria-hidden="true">+</span></summary><p>${q[1]}</p></details>`).join('')}</div></section>
<div class="emergency-note shell"><span class="emergency-cross" aria-hidden="true">✚</span><p><strong>${B('Need urgent care?','ਤੁਰੰਤ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?')}</strong> ${B('For a medical emergency, call our emergency desk or visit your nearest emergency department.','ਐਮਰਜੈਂਸੀ ਲਈ ਸਾਡੇ ਕਾਊਂਟਰ ਨੂੰ ਫ਼ੋਨ ਕਰੋ ਜਾਂ ਨੇੜੇ ਦੇ ਐਮਰਜੈਂਸੀ ਵਿਭਾਗ ਜਾਓ।')}</p><a href="tel:+911814707700">0181-4707700 ${arrow}</a></div></main>
<footer><div class="shell footer-grid"><div><a class="brand footer-brand" href="${prefix}"><img src="${prefix}assets/logo.png" alt="NHS Hospital"></a><p>${B('Specialist care. Human connection.\nHere for your next step.','ਮਾਹਿਰਾਂ ਦੀ ਦੇਖਭਾਲ। ਤੁਹਾਡੇ ਅਗਲੇ ਕਦਮ ਲਈ।')}</p><small>Nasa &amp; Hub Superspeciality Hospital</small></div><div><h3>${B('Explore our care','ਸਾਡੇ ਵਿਭਾਗ')}</h3>${definitions.map(d=>`<a href="${prefix}${d[0]}-treatment/">${B(d[1],d[2])}</a>`).join('')}</div><div><h3>${B('Get in touch','ਸੰਪਰਕ ਕਰੋ')}</h3><a href="tel:+911814633333">${B('Appointments','ਮੁਲਾਕਾਤ')}: 0181-4633333</a><a href="tel:+911814707700">${B('Emergency','ਐਮਰਜੈਂਸੀ')}: 0181-4707700</a><a href="mailto:info@nhshospital.in">info@nhshospital.in</a><p>${B('Near Sports College, Kapurthala Chowk,\nJalandhar, Punjab 144001','ਸਪੋਰਟਸ ਕਾਲਜ ਦੇ ਨੇੜੇ, ਕਪੂਰਥਲਾ ਚੌਕ, ਜਲੰਧਰ')}</p></div></div><div class="shell footer-bottom"><p>${B('General health information only. Consult a qualified doctor for diagnosis and treatment. Care is advised individually; outcomes vary.','ਇਹ ਆਮ ਸਿਹਤ ਜਾਣਕਾਰੀ ਹੈ। ਜਾਂਚ ਅਤੇ ਇਲਾਜ ਲਈ ਯੋਗ ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ ਕਰੋ। ਨਤੀਜੇ ਹਰ ਮਰੀਜ਼ ਲਈ ਵੱਖਰੇ ਹੋ ਸਕਦੇ ਹਨ।')}</p><div><span>© 2026 NHS Hospital, Jalandhar</span><a href="${prefix}privacy.html#privacy">${B('Privacy policy','ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ')}</a><a href="${prefix}privacy.html#terms">${B('Terms','ਨਿਯਮ')}</a></div></div></footer><div class="mobile-actions"><a href="tel:+911814633333">${B('Call our team','ਫ਼ੋਨ ਕਰੋ')}</a><a href="#hero-form">${B('Book a consultation','ਸਲਾਹ ਲਈ ਬਿਨਤੀ')} ${arrow}</a></div></body></html>`;
}
content.forEach((c,i)=>fs.writeFileSync(path.join(root,c.key+'-treatment/index.html'),page(c,definitions[i])));
fs.writeFileSync(path.join(root,'index.html'),page(null,null,true));
fs.mkdirSync(path.join(root,'cardiology'),{recursive:true});
fs.writeFileSync(path.join(root,'cardiology/index.html'),page(content[0],definitions[0]));
for(const d of definitions.slice(1)){
 const legacy=path.join(root,d[0]);
 fs.mkdirSync(legacy,{recursive:true});
 const destination=`../${d[0]}-treatment/`;
 fs.writeFileSync(path.join(legacy,'index.html'),`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${d[1]} | NHS Hospital</title><meta http-equiv="refresh" content="0;url=${destination}"><link rel="canonical" href="https://enquire.nhshospital.in/${d[0]}-treatment/"><script>location.replace(${JSON.stringify(destination)}+location.search+location.hash)</script></head><body><p>This page has moved to <a href="${destination}">NHS Hospital ${d[1]} care</a>.</p></body></html>\n`);
}
console.log('Generated hospital landing page, five specialty pages and cardiology alias.');
