// Page-specific copy and artwork for the shared reference design.
module.exports = {
 cardiology: {
  title: 'Cardiology', titlePa: 'ਦਿਲ ਦੀ ਦੇਖਭਾਲ', icon: 'heart', photo: 'dr-sahil.jpeg',
  heroImage: 'cardiology-heart-hero.png', heroAlt: 'Illustrative photograph of a doctor holding a red heart model',
  headline: 'Protecting <em>hearts.</em><br>Enriching lives.', headlinePa: 'ਦਿਲ ਦੀ ਬਿਹਤਰ ਦੇਖਭਾਲ।<br>ਬਿਹਤਰ ਜੀਵਨ ਵੱਲ।',
  description: 'Specialist expertise and compassionate care. Take the next step for your heart at NHS Hospital, Jalandhar.',
  descriptionPa: 'NHS ਹਸਪਤਾਲ, ਜਲੰਧਰ ਵਿੱਚ ਦਿਲ ਦੇ ਮਾਹਿਰ ਨਾਲ ਆਪਣੀ ਸਿਹਤ ਦੇ ਅਗਲੇ ਕਦਮ ਬਾਰੇ ਗੱਲ ਕਰੋ।',
  trust: 'Specialist-led<br>cardiology', expertise: 'Interventional cardiology',
  services: 'Comprehensive cardiac care under one roof', servicesPa: 'ਇੱਕੋ ਥਾਂ ਦਿਲ ਦੀ ਦੇਖਭਾਲ',
  reassurance: 'Your heart deserves thoughtful care.', reassurancePa: 'ਤੁਹਾਡੇ ਦਿਲ ਲਈ ਖ਼ਾਸ ਦੇਖਭਾਲ।',
  nextStep: 'Take the first step<br>towards a healthier heart.', nextStepPa: 'ਬਿਹਤਰ ਦਿਲ ਦੀ ਸਿਹਤ ਵੱਲ<br>ਪਹਿਲਾ ਕਦਮ ਚੁੱਕੋ।',
  firstCard: ['Heart health<br>consultations', 'ਦਿਲ ਦੀ ਸਿਹਤ ਲਈ ਸਲਾਹ'],
  diagnostic: ['ECG, echo and further evaluation when appropriate.', 'ਲੋੜ ਮੁਤਾਬਕ ECG, ਈਕੋ ਅਤੇ ਹੋਰ ਜਾਂਚ।'],
  treatmentIcons: ['heart', 'clipboard', 'monitor', 'rhythm', 'care', 'leaf'],
 },
 orthopaedics: {
  title: 'Orthopaedics', titlePa: 'ਹੱਡੀਆਂ ਅਤੇ ਜੋੜ', icon: 'joint', photo: 'dr-shubhang.jpg',
  heroImage: 'orthopaedics-hero.png', heroAlt: 'Illustrative photograph of a doctor holding an anatomical knee-joint teaching model',
  headline: 'Moving <em>freely.</em><br>Living fully.', headlinePa: 'ਬਿਹਤਰ ਚੱਲਣ ਵੱਲ।<br>ਬਿਹਤਰ ਜੀਵਨ ਵੱਲ।',
  description: 'From joint pain to sports injuries, take your next step with specialist bone and joint care at NHS Hospital, Jalandhar.',
  descriptionPa: 'ਜੋੜਾਂ ਦੇ ਦਰਦ ਜਾਂ ਖੇਡਾਂ ਦੀ ਸੱਟ ਲਈ NHS ਹਸਪਤਾਲ, ਜਲੰਧਰ ਵਿੱਚ ਹੱਡੀਆਂ ਦੇ ਮਾਹਿਰ ਨਾਲ ਗੱਲ ਕਰੋ।',
  trust: 'Bone &amp; joint<br>specialists', expertise: 'Bone &amp; joint care',
  services: 'Specialist bone and joint care under one roof', servicesPa: 'ਇੱਕੋ ਥਾਂ ਹੱਡੀਆਂ ਅਤੇ ਜੋੜਾਂ ਦੀ ਦੇਖਭਾਲ',
  reassurance: 'Every step deserves thoughtful care.', reassurancePa: 'ਤੁਹਾਡੇ ਹਰ ਕਦਮ ਲਈ ਖ਼ਾਸ ਦੇਖਭਾਲ।',
  nextStep: 'Take the first step<br>towards better movement.', nextStepPa: 'ਬਿਹਤਰ ਚੱਲਣ ਵੱਲ<br>ਪਹਿਲਾ ਕਦਮ ਚੁੱਕੋ।',
  firstCard: ['Bone &amp; joint<br>consultations', 'ਹੱਡੀਆਂ ਅਤੇ ਜੋੜਾਂ ਲਈ ਸਲਾਹ'],
  diagnostic: ['Clinical assessment and imaging to understand your joint concerns.', 'ਜੋੜਾਂ ਦੀ ਸਮੱਸਿਆ ਲਈ ਮਾਹਿਰ ਦੀ ਜਾਂਚ ਅਤੇ ਸਕੈਨ।'],
  treatmentIcons: ['joint', 'joint', 'bone', 'activity', 'bone', 'shield'],
 },
 urology: {
  title: 'Urology', titlePa: 'ਯੂਰੋਲੋਜੀ', icon: 'urinary', photo: 'dr-satinder.jpeg',
  heroImage: 'urology-hero.png', heroAlt: 'Illustrative photograph of a doctor holding a kidneys, ureters and bladder teaching model',
  headline: 'Expert <em>urology.</em><br>Personal care.', headlinePa: 'ਪਿਸ਼ਾਬ ਰੋਗਾਂ ਲਈ ਸਲਾਹ।<br>ਤੁਹਾਡੇ ਲਈ ਦੇਖਭਾਲ।',
  description: 'Get a clear plan for kidney stones, prostate concerns and urinary health with a specialist at NHS Hospital, Jalandhar.',
  descriptionPa: 'ਪੱਥਰੀ, ਪ੍ਰੋਸਟੇਟ ਅਤੇ ਪਿਸ਼ਾਬ ਦੀ ਸਮੱਸਿਆ ਲਈ NHS ਹਸਪਤਾਲ, ਜਲੰਧਰ ਵਿੱਚ ਮਾਹਿਰ ਦੀ ਸਲਾਹ ਲਵੋ।',
  trust: 'Specialist-led<br>urology', expertise: 'Urinary &amp; surgical care',
  services: 'Comprehensive urology care under one roof', servicesPa: 'ਇੱਕੋ ਥਾਂ ਪਿਸ਼ਾਬ ਰੋਗਾਂ ਦੀ ਦੇਖਭਾਲ',
  reassurance: 'Clear answers. Care built around you.', reassurancePa: 'ਸਪੱਸ਼ਟ ਸਲਾਹ। ਤੁਹਾਡੇ ਲਈ ਦੇਖਭਾਲ।',
  nextStep: 'Take the first step<br>for your urinary health.', nextStepPa: 'ਪਿਸ਼ਾਬ ਦੀ ਸਿਹਤ ਲਈ<br>ਪਹਿਲਾ ਕਦਮ ਚੁੱਕੋ।',
  firstCard: ['Urinary health<br>consultations', 'ਪਿਸ਼ਾਬ ਦੀ ਸਿਹਤ ਲਈ ਸਲਾਹ'],
  diagnostic: ['Specialist evaluation and investigations when appropriate.', 'ਲੋੜ ਅਨੁਸਾਰ ਮਾਹਿਰ ਦੀ ਸਲਾਹ ਅਤੇ ਜਾਂਚ।'],
  treatmentIcons: ['kidneys', 'scope', 'kidneys', 'urinary', 'scope', 'shield'],
 },
 nephrology: {
  title: 'Nephrology', titlePa: 'ਗੁਰਦਿਆਂ ਦੀ ਦੇਖਭਾਲ', icon: 'kidneys', photo: 'dr-sanjay.jpeg',
  heroImage: 'nephrology-hero.png', heroAlt: 'Illustrative photograph of a doctor holding whole and cutaway kidney teaching models',
  headline: 'Your <em>kidneys.</em><br>Our complete focus.', headlinePa: 'ਤੁਹਾਡੇ ਗੁਰਦਿਆਂ ਦੀ ਸਿਹਤ।<br>ਸਾਡੀ ਖ਼ਾਸ ਦੇਖਭਾਲ।',
  description: 'Make sense of your kidney reports and explore ongoing care, dialysis and treatment planning at NHS Hospital, Jalandhar.',
  descriptionPa: 'ਗੁਰਦਿਆਂ ਦੀਆਂ ਰਿਪੋਰਟਾਂ, ਡਾਇਲਸਿਸ ਅਤੇ ਲਗਾਤਾਰ ਦੇਖਭਾਲ ਲਈ NHS ਹਸਪਤਾਲ, ਜਲੰਧਰ ਵਿੱਚ ਮਾਹਿਰ ਨਾਲ ਗੱਲ ਕਰੋ।',
  trust: 'Kidney care<br>specialists', expertise: 'Kidney &amp; dialysis care',
  services: 'Complete kidney care under one roof', servicesPa: 'ਇੱਕੋ ਥਾਂ ਗੁਰਦਿਆਂ ਦੀ ਦੇਖਭਾਲ',
  reassurance: 'Ongoing support for your kidney health.', reassurancePa: 'ਗੁਰਦਿਆਂ ਦੀ ਸਿਹਤ ਲਈ ਲਗਾਤਾਰ ਸਹਾਇਤਾ।',
  nextStep: 'Take the first step<br>for your kidney health.', nextStepPa: 'ਗੁਰਦਿਆਂ ਦੀ ਸਿਹਤ ਲਈ<br>ਪਹਿਲਾ ਕਦਮ ਚੁੱਕੋ।',
  firstCard: ['Kidney health<br>consultations', 'ਗੁਰਦਿਆਂ ਦੀ ਸਿਹਤ ਲਈ ਸਲਾਹ'],
  diagnostic: ['Review your kidney function, blood tests and urine reports.', 'ਗੁਰਦਿਆਂ ਦੀ ਸਿਹਤ, ਖ਼ੂਨ ਅਤੇ ਪਿਸ਼ਾਬ ਦੀਆਂ ਰਿਪੋਰਟਾਂ ਬਾਰੇ ਸਲਾਹ।'],
  treatmentIcons: ['dialysis', 'monitor', 'clipboard', 'dialysis', 'kidneys', 'care'],
 },
 gastroenterology: {
  title: 'Gastroenterology', titlePa: 'ਪੇਟ ਅਤੇ ਜਿਗਰ', icon: 'stomach', photo: 'dr-anuj.jpeg',
  heroImage: 'gastroenterology-hero.png', heroAlt: 'Illustrative photograph of a doctor holding a liver, stomach and pancreas teaching model',
  headline: 'Better <em>digestion.</em><br>Better living.', headlinePa: 'ਪੇਟ ਅਤੇ ਜਿਗਰ ਦੀ ਸਿਹਤ।<br>ਬਿਹਤਰ ਜੀਵਨ ਵੱਲ।',
  description: 'Understand digestive symptoms, liver reports and treatment options with specialist care at NHS Hospital, Jalandhar.',
  descriptionPa: 'ਪੇਟ ਦੀ ਤਕਲੀਫ਼, ਜਿਗਰ ਦੀਆਂ ਰਿਪੋਰਟਾਂ ਅਤੇ ਇਲਾਜ ਲਈ NHS ਹਸਪਤਾਲ, ਜਲੰਧਰ ਵਿੱਚ ਮਾਹਿਰ ਨਾਲ ਗੱਲ ਕਰੋ।',
  trust: 'Digestive care<br>specialists', expertise: 'Digestive &amp; liver care',
  services: 'Digestive and liver care under one roof', servicesPa: 'ਇੱਕੋ ਥਾਂ ਪੇਟ ਅਤੇ ਜਿਗਰ ਦੀ ਦੇਖਭਾਲ',
  reassurance: 'Feel heard. Find a clear next step.', reassurancePa: 'ਤੁਹਾਡੀ ਗੱਲ ਸੁਣੀਏ। ਅਗਲਾ ਕਦਮ ਚੁਣੀਏ।',
  nextStep: 'Take the first step<br>for your digestive health.', nextStepPa: 'ਪੇਟ ਦੀ ਸਿਹਤ ਲਈ<br>ਪਹਿਲਾ ਕਦਮ ਚੁੱਕੋ।',
  firstCard: ['Digestive health<br>consultations', 'ਪੇਟ ਦੀ ਸਿਹਤ ਲਈ ਸਲਾਹ'],
  diagnostic: ['Endoscopy, scans and further evaluation when indicated.', 'ਲੋੜ ਅਨੁਸਾਰ ਐਂਡੋਸਕੋਪੀ, ਸਕੈਨ ਅਤੇ ਹੋਰ ਜਾਂਚ।'],
  treatmentIcons: ['scope', 'liver', 'stomach', 'liver', 'scope', 'leaf'],
 },
};
